#pragma once

#define MG_ARCH MG_ARCH_RP2040
#define MG_ENABLE_SOCKET 0
#define MG_ENABLE_TCPIP 1
#define MG_IO_SIZE 128
//#define MG_ENABLE_LOG 0

#define MG_ENABLE_PACKED_FS 1
// #define MG_TLS MG_TLS_BUILTIN

#define MG_OTA MG_OTA_CUSTOM
#define MG_DEVICE MG_DEVICE_CUSTOM